version: "3.8"

services:
  rabbitmq1:
    container_name: rabbitmq1
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=BBRPCLNQOARERAQXUHXG